version: '3.8'

services:
  frontend:
    build:
      context: ./event_manager_client
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: npm start
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: EventsDataBase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  pgdata:
